### ISSUE TITLE
data postprocess error

### ISSUE THREAD

**Issue by QJohn2017** [brownjm/laser-propagation#1]
Hi, thank you for providing this laser propagation code. When I do a simulation and do the data postprocess, some errors occured:
1. when I open the gui.py plotting , the gui appeared as follows:
![image](https://user-images.githubusercontent.com/31507149/89869773-6bc19b00-dbe7-11ea-9fca-b36f4581dc68.png)
And I open the output file "E004.dat",and click any one of  the buttom modules, there is nothing appeared and any errors occured. So, what is the problem?
2. when I use the command "results = load.Results('rs\E004.dat')" in Python, the erros below occured:
![image](https://user-images.githubusercontent.com/31507149/89870083-e8ed1000-dbe7-11ea-8da1-b8ad828d5f68.png)
So, how can I do?

Thank you very much!

**Comment by brownjm** [comment]
Hi, I'm glad that you're finding the code useful. Could you provide me some more information for item 1? Try launching python gui.py from the command line. That way if any errors occur, then you should see the error printed in the command line window.

For item 2, you are not using load.Results() correctly. To create a Results object, you should not pass a field filename (E004.dat) as an argument. Instead pass in the filename of your input file (the file that contains the inputs for the simulation). Once you have the results object, then you specify which field (electric, spectral, electron density) and at what distance you'd like to inspect it. The code should look like this:
```python
import load

filename = 'my_input_filename'
requested_distance = 0.2

results = load.Results(filename)
z, E = results.electric_field(requested_distance)
# z is the closest propagation distance to the requested one, E contains the electric field
```
Please let me know if this fixes your issues and/or if you have any more questions.

**Comment by QJohn2017** [comment]
@brownjm Thank you very much for your reply. the issue 2 is resolved, but for the issue 1, there is no errors occured when I launch  python gui.py from the command line. 
![image](https://user-images.githubusercontent.com/31507149/90211604-c21b1d80-de23-11ea-86dd-c1e021a2d119.png)
 I don't know whether the  input file in the GUI is 'my_input_filename' or  field filename (E004.dat) . Actually, both of the two files I have already tried , but theere is nothing appeared when i click the modules in the buttom of the GUI
