### ISSUE TITLE
Memory access error in energy calculation

### ISSUE THREAD

**Issue by anates** [brownjm/laser-propagation#2]
Assumed I understand the code correctly, wouldn't the following part in utils.cc
```
  double integral = 0;
  for (int i = field.Nradius-1; i >=0; --i) {
    integral += (radius[i]*aux[i] + radius[i-1]*aux[i-1]) / 2 * (radius[i] - radius[i-1]);
  }
```
result in a bad memory access? `i` will iterate down to 0, resulting in a memory access at `radius[-1]`. Is that intended, or should the loop rather be written as 
```
for (int i = field.Nradius-1; i >0; --i)
```
Thanks!

**Comment by brownjm** [comment]
Yes, this is indeed a bug. Thanks for finding it! I've applied the fix in branches master and develop.
