### ISSUE TITLE
Cannot open input file

### ISSUE THREAD

**Issue by hfdihfd** [brownjm/laser-propagation#3]
Thanks a lot for your codes. But I may have a really stupid question. When I use an input file after ./main.out it always prompts that the input file cannot be opened. I'm not proficient in c++ and I don't know what to do. So I want to consult you.

**Comment by hfdihfd** [comment]
![屏幕截图 2022-06-13 160034](https://user-images.githubusercontent.com/106145313/173307535-b66095ff-bfa0-43c7-aaea-144977fe413c.jpg)
The main.out file has been generated in the build folder as required. 
I copy the input file under examples folder to the build folder, but I can't get the correct result when I execute ./main.out [input]
I don't know what's wrong

**Comment by brownjm** [comment]
Hi, thanks for submitting a screenshot. Remove the square brackets around 'input' and the code should run. The symbols [] are not allowed in filenames. Looking at the README file, I can see why you might want to write it that way. I'll update the README to have clearer instructions.
Does it work after this change?

**Comment by hfdihfd** [comment]
> 您好，感谢您提交屏幕截图。删除“输入”周围的方括号，代码应该运行。文件名中不允许使用符号 []。查看 README 文件，我可以明白您为什么要这样写。我将更新自述文件以获得更清晰的说明。 这个改动后有用吗？

Thank you very much for your reply, it's really useful.
Also I found a small problem
![1](https://user-images.githubusercontent.com/106145313/173415937-2d8b0b0a-688d-43c8-a7ce-2a66669f182b.jpg).
Clicking E(r,t) will report an error.
I think maybe this sentence is unnecessary?
![2](https://user-images.githubusercontent.com/106145313/173416348-c9a8dea3-bbd5-4ff3-b303-36034233255d.jpg)

ρ(r,t) is the same.

**Comment by brownjm** [comment]
Please open a new issue when a new problem arises. Thanks for the fix, I've updated temporal.py.
